### ISSUE TITLE
Replacing ceph-cookbook with ceph-chef more information needed.

### ISSUE THREAD

**Issue by krenakzsolt** [ceph/ceph-chef#25]
Hi All!

The readme mentions, that simply replacing the old cookbook is not possible without modifications. Could someone share some details about this modifications? What should I look for?

**Comment by cloudm2** [comment]
The main thing is the osd device attributes. More options were added. You
can create a branch on your device and see where may fail. The only real
concerns will be any interfaces you may have used like pool resource etc.
They all had additional options added.

Thanks

On Monday, April 25, 2016, krenakzsolt <notifications@github.com> wrote:

> Hi All!
>
> The readme mentions, that simply replacing the old cookbook is not
> possible without modifications. Could someone share some details about this
> modifications? What should I look for?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph-chef/issues/25>
>


-- 
Best Regards,
Chris Jones

cjones@cloudm2.com
(p) 770.655.0770

**Comment by krenakzsolt** [comment]
Thanks for the answer! These new OSD device attriubutes shouldn't effect already active and deployed OSDs aren't they?

**Comment by cloudm2** [comment]
Correct. There is a guard for each device. However, we have not tested
using the cookbooks against an existing cluster.

Thanks

On Tuesday, April 26, 2016, krenakzsolt <notifications@github.com> wrote:

> Thanks for the answer! These new OSD device attriubutes shouldn't effect
> already active and deployed OSDs aren't they?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/ceph/ceph-chef/issues/25#issuecomment-214659919>
>


-- 
Best Regards,
Chris Jones

cjones@cloudm2.com
(p) 770.655.0770

**Comment by cloudm2** [comment]
Issue resolved
