### ISSUE TITLE
bloomberg.ca.pem must exist

### ISSUE THREAD

**Issue by maumenee** [ceph/ceph-chef#27]
This is probably a simple mistake on my part, but I am getting stopped after I run ./CEPH_UP with the error message:

There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
* File upload source file /Users/../../chef-bcs/certs/bloomberg.ca.pem must exist
* File upload source file /Users/../../chef-bcs/certs/bloomberg.intermediate.ca.pem must exist

This happens even when I am not behind a proxy and/or firewall.

Any advice on how to fix this would be much appreciated.

Thanks!

**Comment by cloudm2** [comment]
This issue belong at https://github.com/bloomberg/chef-bcs/issues. It relates to the environment.yaml file.  Can you open it there?
Thanks

**Comment by maumenee** [comment]
Thanks so much.
That worked great!
