### ISSUE TITLE
bootstrap-osd keys not created

### ISSUE THREAD

**Issue by joerocklin** [ceph/ceph-chef#31]
I'm trying to bootstrap a new cluster, and among other problems I noticed that the bootstrap-osd keys aren't being created. I'm running v0.9.26 from supermarket trying to install Jewel on CentOS 7.2. Specifically, I'm curious about the updates that happened in 6800cc31002f2cc596e5ba8b78853a42f6b37da6 which changed the way the [bootstrap-osd key is created](https://github.com/ceph/ceph-chef/commit/6800cc31002f2cc596e5ba8b78853a42f6b37da6#diff-59d3c57f410da06df0d8d9488d620513R39) from:

```
BOOTSTRAP_KEY=`ceph --name mon. --keyring /etc/ceph/#{node['ceph']['cluster']}.mon.keyring auth get-or-create-key client.bootstrap-osd mon 'allow profile bootstrap-osd'`
```

to

```
BOOTSTRAP_KEY=$(ceph-authtool "/etc/ceph/#{node['ceph']['cluster']}.mon.keyring" -n mon. -p)
```

Maybe I'm missing something obvious, but it seems like this (and the other keys which are created in a similar manner) are not actually being added to ceph (I see no `ceph auth import` anywhere which might be importing them). The comments on the commit don't provide any insight into the change, so can you help me understand what's going on?

**Comment by cloudm2** [comment]
Jewel update has not been released yet but will soon. However, I will take
a look at that change.

Thanks

On Thursday, June 30, 2016, Joe Rocklin <notifications@github.com> wrote:

> I'm trying to bootstrap a new cluster, and among other problems I noticed
> that the bootstrap-osd keys aren't being created. I'm running v0.9.26 from
> supermarket trying to install Jewel on CentOS 7.2. Specifically, I'm
> curious about the updates that happened in 6800cc3
> <https://github.com/ceph/ceph-chef/commit/6800cc31002f2cc596e5ba8b78853a42f6b37da6>
> which changed the way the bootstrap key is created
> <https://github.com/ceph/ceph-chef/commit/6800cc31002f2cc596e5ba8b78853a42f6b37da6#diff-59d3c57f410da06df0d8d9488d620513R39>
> from:
>
> BOOTSTRAP_KEY=`ceph --name mon. --keyring /etc/ceph/#{node['ceph']['cluster']}.mon.keyring auth get-or-create-key client.bootstrap-osd mon 'allow profile bootstrap-osd'`
>
> to
>
> BOOTSTRAP_KEY=$(ceph-authtool "/etc/ceph/#{node['ceph']['cluster']}.mon.keyring" -n mon. -p)
>
> Maybe I'm missing something obvious, but it seems like this (and the other
> keys which are created in a similar manner) are not actually being added to
> ceph (I see no ceph auth import anywhere which might be importing them).
> The comments on the commit don't provide any insight into the change, so
> can you help me understand what's going on?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/ceph/ceph-chef/issues/31>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAhgSHDSJslnWVoLnpo_e3Q4ZH_zocBmks5qRAu2gaJpZM4JCc0o>
> .
>


-- 
Best Regards,
Chris Jones

cjones@cloudm2.com
(p) 770.655.0770

**Comment by joerocklin** [comment]
Is there another repo I can look to for the Jewel support? I'm in the process of working through creating a wrapper cookbook to do all of the pieces I find missing, and I'd like to either a) have those be part of the community cookbook, or b) not have to re-do everything once community support for jewel is in place.

(it might also be useful to update the Readme section to specifically call out the versions support instead of just saying 'Hammer or higher')

**Comment by cloudm2** [comment]
Sorry for the delay. Not sure of other chef code for jewel. Please feel
free to issue pull requests for enhancements. Ceph made several structural
changes etc for Jewel which created a bit more work than expected. That
said, there are some basic enhancements already there such as changing
owner and group names since the jewel version uses the ceph user instead of
root. Again, please feel free to issue pull requests!

Thanks

On Friday, July 1, 2016, Joe Rocklin <notifications@github.com> wrote:

> Is there another repo I can look to for the Jewel support? I'm in the
> process of working through creating a wrapper cookbook to do all of the
> pieces I find missing, and I'd like to either a) have those be part of the
> community cookbook, or b) not have to re-do everything once community
> support for jewel is in place.
>
> (it might also be useful to update the Readme section to specifically call
> out the versions support instead of just saying 'Hammer or higher')
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ceph/ceph-chef/issues/31#issuecomment-229924971>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAhgSHLb64rmU8vCEBaxZY_XJDJn6BQnks5qRPs_gaJpZM4JCc0o>
> .
>


-- 
Best Regards,
Chris Jones

cjones@cloudm2.com
(p) 770.655.0770

**Comment by joerocklin** [comment]
FYI - I've started merging some of work back in over at https://github.com/joerocklin/ceph-chef/tree/jewel
