### ISSUE TITLE
Request for discussion/documentation of migration issues from ceph-cookbook

### ISSUE THREAD

**Issue by mdsteveb** [ceph/ceph-chef#49]
I have a production Hammer cluster (mostly RBD, possibly expanding to include CephFS in the future) built with ceph-cookbook.

As I'm looking at paths forward to Jewell and beyond, I'm wondering if I should also be migrating to a more complete/up-to-date chef cookbook, so I would like to hear more about the differences between these two cookbooks and how one might migrate an existing ceph-cookbook cluster to ceph-chef.  So far I haven't found any real discussion about this; any pointers to previous discussions would also be appreciated.

On the surface they appear very similar, except for the comment in the README that they're not directly compatible.

Thanks.

**Comment by mdsteveb** [comment]
Oops.  And of course having posted this I just found the closed issue on this topic.  Is that really the extent of the issues though?

**Comment by hanscj1** [comment]
Sorry the delay! The difference between the two would make for a challenging migration. It would be good to have ceph-chef to read an existing cluster and build it's internals :).
