### ISSUE TITLE
ceps-mon IO error Permission deny

### ISSUE THREAD

**Issue by cyberflow** [ceph/ceph-chef#57]
When i try to use mon recipe for configuring monitor i had error in service log:
```ceph-mon[10420]: IO error: /var/lib/ceph/mon/ceph-defaultubuntu16-cyberflow-macbookairdmitrylocal-6i41frd/store.db/LOCK: Permission deny```

I think that it's because execute block 'ceph-mon mkfs' in mon recipe executing command by user root.

**Comment by hanscj1** [comment]
Is this Jewel?

**Comment by cyberflow** [comment]
@hanscj1 yes, it is.

**Comment by hanscj1** [comment]
The default install is for Hammer. IIRC, you can set the default vars to Jewel which should replace the older 'root' with the newer 'ceph' user. If you see something that needs fixed or added then please: fork, create feature branch, make your changes and test, issue pull request. Thanks!

**Comment by cyberflow** [comment]
@hanscj1 i'm added PR with change user for executing resources, but it still not solve problem, because *.mon.keyring located in `/etc/ceph/' path and not available for user ceph there.
