### ISSUE TITLE
OSD Daemon Looks for Keyring in Wrong Location

### ISSUE THREAD

**Issue by rdgold94** [ceph/ceph-chef#99]
Not sure if this is a bug or a problem with my configuration, but I'm running into this issue consistently.

I'm trying to start 1 Ceph Jewel monitor and OSD on a single CentOS 7 node, using these recipes in my runlist:

1. ceph-chef::mon
2. ceph-chef::mon_start
3. ceph-chef::osd

The monitor comes up correctly, and the OSD is added to the CRUSH map. However, the OSD daemon fails to start. A `systemctl status ceph-osd@0.service` reveals

>  2017-06-08 17:23:26.790379 7faaa6c35800 -1 auth: unable to find a keyring on /etc/ceph/ceph.osd.0.keyring: (2) No such file or directory

even though the keyring is clearly being created in the daemon's data directory, which is as expected when using the ceph-disk utility: 

> /var/lib/ceph/osd/ceph-0/keyring 

I was able to solve this issue by copying the keyring in the data directory to "/etc/ceph/ceph.osd.0.keyring" and changing the ownership of the file to ceph:ceph. However, this is obviously very hacky, and I cannot figure out what about my configuration is causing the OSD daemon to look in a different directory for its keyring.

**Comment by rdgold94** [comment]
I think this problem is due to a line that is being generated in the "ceph.conf" file:

> keyring = /etc/ceph/$cluster.$name.keyring

This probably should not be created in the [global] section, because it causes the OSD keyring to look in the /etc/ directory when it should be looking in the daemon's data directory.

**Comment by hanscj1** [comment]
Keyrings can actually be anywhere per se. They can reside in /etc/ceph for easy maintenance or in /var/lib/ceph/[osd, mon ...] or anywhere you wish as long as permissions are set correctly. The two place mentioned are the most common. The ceph.conf should actually allow the calling recipes the ability to set the path they want and not be so opinionated.

**Comment by hanscj1** [comment]
The project cepheus does a lot of this based on yaml data. I will make the change to default the path but allow for overrides in calling recipes. https://github.com/cepheus-io.

**Comment by hanscj1** [comment]
Defaults have now been set for each in the default.rb in attributes. These can be overridden if desired by the calling recipe. If there is an issue then please open another ticket. thx
